// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBCn1rKDNUCrysxpLIzL5HA03gRFU8_E',
    appId: '1:1050335747127:web:69221d9d4fc5ea16d0b3b2',
    messagingSenderId: '1050335747127',
    projectId: 'flutter-chat-app-9fef0',
    authDomain: 'flutter-chat-app-9fef0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9fef0.firebasestorage.app',
    measurementId: 'G-JHGYHKL73H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUWcXiqS6t0qc9nBIitRWHI28dYniQXCg',
    appId: '1:1050335747127:android:9d08a3b3d4a158c4d0b3b2',
    messagingSenderId: '1050335747127',
    projectId: 'flutter-chat-app-9fef0',
    storageBucket: 'flutter-chat-app-9fef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uGLpDV31Ni_8Wv-BqgxR1ocxhwmtl2M',
    appId: '1:1050335747127:ios:82a6845440f598dcd0b3b2',
    messagingSenderId: '1050335747127',
    projectId: 'flutter-chat-app-9fef0',
    storageBucket: 'flutter-chat-app-9fef0.firebasestorage.app',
    iosBundleId: 'com.technicalencoder.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uGLpDV31Ni_8Wv-BqgxR1ocxhwmtl2M',
    appId: '1:1050335747127:ios:df6c16b3d90ecd56d0b3b2',
    messagingSenderId: '1050335747127',
    projectId: 'flutter-chat-app-9fef0',
    storageBucket: 'flutter-chat-app-9fef0.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTBCn1rKDNUCrysxpLIzL5HA03gRFU8_E',
    appId: '1:1050335747127:web:b01911dad77c11b0d0b3b2',
    messagingSenderId: '1050335747127',
    projectId: 'flutter-chat-app-9fef0',
    authDomain: 'flutter-chat-app-9fef0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9fef0.firebasestorage.app',
    measurementId: 'G-ZD2Q926BY4',
  );
}
